# Generated by Django 3.0.5 on 2020-07-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20200707_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated']},
        ),
    ]
